name: Publish

on:
  push:
    tags:
    - v**.**.**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        scope: "@cactusoft-ca"
        node-version: 14.x

    - name: "Setup git"
      run: |
        git config user.email "developers@cactusoft.ca"
        git config user.name "Cactusoft Package Manager"

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build
      run: npm run build:prod --if-present
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Publish
      working-directory: ./dist/ng-miniprofiler
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
